export default {
  SHOW_MODAL: 'SHOW_MODAL',
  HIDE_MODAL: 'HIDE_MODAL',
  UPDATE_MODAL_SIZE: 'UPDATE_MODAL_SIZE',

  CLEAR_CACHE: 'CLEAR_CACHE',

  AUTH_SUCCESSFULL: 'AUTH_SUCCESSFULL',
  AUTH_LOGOUT: 'AUTH_LOGOUT',
  AUTH_REFRESH_TOKEN_PROMISES: 'AUTH_REFRESH_TOKEN_PROMISES',
  AUTH_SIS_LISTE: 'AUTH_SIS_LISTE',
  AUTH_SELECT_SIS: 'AUTH_SELECT_SIS',
  AUTH_PERMISSIONS_LISTE: 'AUTH_PERMISSIONS_LISTE',
  AUTH_ROLES_LISTE: 'AUTH_ROLES_LISTE',
  AUTH_USERS_LISTE: 'AUTH_USERS_LISTE',
  UPDATE_USER_ROLE: 'UPDATE_USER_ROLE',

  ADD_SIS: 'ADD_SIS',
  EDIT_SIS: 'EDIT_SIS',
  ADMIN_USER_LISTE: 'ADMIN_USER_LISTE',
  ADMIN_EDIT_USER: 'ADMIN_EDIT_USER',
  ADMIN_REMOVE_USER: 'ADMIN_REMOVE_USER',

  ADD_ROLE: 'ADD_ROLE',
  UPDATE_ROLE: 'UPDATE_ROLE',
  DELETE_ROLE: 'DELETE_ROLE',

  // MES INFOS
  UPDATE_MES_INFOS: 'UPDATE_MES_INFOS',
  UPDATE_MES_COURS: 'UPDATE_MES_COURS',
  UPDATE_MES_FONCTIONS: 'UPDATE_MES_FONCTIONS',
  UPDATE_MES_GRADES: 'UPDATE_MES_GRADES',
  UPDATE_MES_GROUPES: 'UPDATE_MES_GROUPES',
  UPDATE_MES_MUTATIONS: 'UPDATE_MES_MUTATIONS',
  UPDATE_MON_MATERIEL: 'UPDATE_MON_MATERIEL',
  UPDATE_MES_TRAVAUX: 'UPDATE_MES_TRAVAUX',
  UPDATE_MES_EXERCICES: 'UPDATE_MES_EXERCICES',
  UPDATE_MES_INTERVENTIONS: 'UPDATE_MES_INTERVENTIONS',
  UPDATE_MES_PAIEMENTS: 'UPDATE_MES_PAIEMENTS',
  UPDATE_MES_ECRITURES: 'UPDATE_MES_ECRITURES',

  // RTA
  UPDATE_RTA_REFERENCE_RTA: 'UPDATE_RTA_REFERENCE_RTA',
  UPDATE_RTA_REFERENCE_GESTSIS: 'UPDATE_RTA_REFERENCE_GESTSIS',

  // Global Params
  UPDATE_SIS_PARAMS: 'UPDATE_SIS_PARAMS',
  UPDATE_AVS_PARAMS: 'UPDATE_AVS_PARAMS',
  UPDATE_EXCUSE_PARAMS: 'UPDATE_EXCUSE_PARAMS',
  UPDATE_LOCALITE_SIS_LISTE: 'UPDATE_LOCALITE_SIS_LISTE',

  // Sapeurs base data
  UPDATE_PERMIS_LISTE: 'UPDATE_PERMIS_LISTE',
  UPDATE_TELEPHONE_TYPE_LISTE: 'UPDATE_TELEPHONE_TYPE_LISTE',
  UPDATE_CIVILITE_LISTE: 'UPDATE_CIVILITE_LISTE',
  UPDATE_LOCALITE_LISTE: 'UPDATE_LOCALITE_LISTE',
  UPDATE_COURS_LISTE: 'UPDATE_COURS_LISTE',
  ADD_COURS: 'ADD_COURS',
  UPDATE_COURS: 'UPDATE_COURS',
  REMOVE_COURS: 'REMOVE_COURS',
  UPDATE_GRADE_LISTE: 'UPDATE_GRADE_LISTE',
  ADD_GRADE: 'ADD_GRADE',
  UPDATE_GRADE: 'UPDATE_GRADE',
  REMOVE_GRADE: 'REMOVE_GRADE',
  UPDATE_FONCTION_LISTE: 'UPDATE_FONCTION_LISTE',
  ADD_FONCTION: 'ADD_FONCTION',
  UPDATE_FONCTION: 'UPDATE_FONCTION',
  REMOVE_FONCTION: 'REMOVE_FONCTION',

  // Groupes
  UPDATE_GROUPE_LISTE: 'UPDATE_GROUPE_LISTE',
  CREATE_GROUPE: 'CREATE_GROUPE',
  UPDATE_GROUPE: 'UPDATE_GROUPE',
  DELETE_GROUPE: 'DELETE_GROUPE',
  UPDATE_GROUPE_SAPEURS: 'UPDATE_GROUPE_SAPEURS',

  // Exercices Params
  SELECT_EXCUSE_TYPE: 'SELECT_EXCUSE_TYPE',
  UPDATE_EXCUSE_TYPE_LISTE: 'UPDATE_EXCUSE_TYPE_LISTE',
  ADD_EXCUSE_TYPE: 'ADD_EXCUSE_TYPE',
  UPDATE_EXCUSE_TYPE: 'UPDATE_EXCUSE_TYPE',
  REMOVE_EXCUSE_TYPE: 'REMOVE_EXCUSE_TYPE',
  UPDATE_EXERCICE_CATEGORIE_LISTE: 'UPDATE_EXERCICE_CATEGORIE_LISTE',
  ADD_EXERCICE_CATEGORIE: 'ADD_EXERCICE_CATEGORIE',
  UPDATE_EXERCICE_CATEGORIE: 'UPDATE_EXERCICE_CATEGORIE',
  REMOVE_EXERCICE_CATEGORIE: 'REMOVE_EXERCICE_CATEGORIE',
  UPDATE_HEURE_EXERCICE_LISTE: 'UPDATE_HEURE_EXERCICE_LISTE',
  ADD_HEURE_EXERCICE: 'ADD_HEURE_EXERCICE',
  UPDATE_HEURE_EXERCICE: 'UPDATE_HEURE_EXERCICE',
  REMOVE_HEURE_EXERCICE: 'REMOVE_HEURE_EXERCICE',
  UPDATE_ASPSMS_PARAMS: 'UPDATE_ASPSMS_PARAMS',
  UPDATE_ASPSMS_CREDIT: 'UPDATE_ASPSMS_CREDIT',

  // Sapeurs edit
  CREATE_SAPEUR: 'CREATE_SAPEUR',
  DELETE_SAPEUR: 'DELETE_SAPEUR',
  SELECT_CURRENT_SAPEUR: 'SELECT_CURRENT_SAPEUR',
  UPDATE_SAPEURS_LISTE: 'UPDATE_SAPEURS_LISTE',
  UPDATE_CURRENT_SAPEUR_DATA: 'UPDATE_CURRENT_SAPEUR_DATA',
  UPDATE_CURRENT_SAPEUR_PERMIS: 'UPDATE_CURRENT_SAPEUR_PERMIS',
  UPDATE_CURRENT_SAPEUR_TELEPHONES: 'UPDATE_CURRENT_SAPEUR_TELEPHONES',
  UPDATE_CURRENT_SAPEUR_GROUPES: 'UPDATE_CURRENT_SAPEUR_GROUPES',
  UPDATE_CURRENT_SAPEUR_GRADES: 'UPDATE_CURRENT_SAPEUR_GRADES',
  UPDATE_CURRENT_SAPEUR_FONCTIONS: 'UPDATE_CURRENT_SAPEUR_FONCTIONS',
  UPDATE_CURRENT_SAPEUR_MUTATIONS: 'UPDATE_CURRENT_SAPEUR_MUTATIONS',
  UPDATE_CURRENT_SAPEUR_CONTROLES_MEDICAUX:
    'UPDATE_CURRENT_SAPEUR_CONTROLES_MEDICAUX',
  UPDATE_CURRENT_SAPEUR_MATERIELS: 'UPDATE_CURRENT_SAPEUR_MATERIELS',
  UPDATE_CURRENT_SAPEUR_BANQUE: 'UPDATE_CURRENT_SAPEUR_BANQUE',
  UPDATE_CURRENT_SAPEUR_COURS: 'UPDATE_CURRENT_SAPEUR_COURS',
  UPDATE_CURRENT_SAPEUR_EXERCICES: 'UPDATE_CURRENT_SAPEUR_EXERCICES',

  UPDATE_CURRENT_FONCTION: 'UPDATE_CURRENT_FONCTION',
  UPDATE_CURRENT_GRADE: 'UPDATE_CURRENT_GRADE',
  UPDATE_CURRENT_COURS: 'UPDATE_CURRENT_COURS',
  UPDATE_CURRENT_MUTATION: 'UPDATE_CURRENT_MUTATION',
  UPDATE_CURRENT_PHASE: 'UPDATE_CURRENT_PHASE',

  REMOVE_CURRENT_INTERVENTION_PHASE: 'REMOVE_CURRENT_INTERVENTION_PHASE',

  ADD_CURRENT_SAPEUR_MUTATION: 'ADD_CURRENT_SAPEUR_MUTATION',
  EDIT_CURRENT_SAPEUR_MUTATION: 'EDIT_CURRENT_SAPEUR_MUTATION',
  REMOVE_CURRENT_SAPEUR_MUTATION: 'REMOVE_CURRENT_SAPEUR_MUTATION',

  ADD_CURRENT_SAPEUR_PERMIS: 'ADD_CURRENT_SAPEUR_PERMIS',
  EDIT_CURRENT_SAPEUR_PERMIS: 'EDIT_CURRENT_SAPEUR_PERMIS',
  REMOVE_CURRENT_SAPEUR_PERMIS: 'REMOVE_CURRENT_SAPEUR_PERMIS',

  ADD_CURRENT_SAPEUR_TELEPHONE: 'ADD_CURRENT_SAPEUR_TELEPHONE',
  EDIT_CURRENT_SAPEUR_TELEPHONE: 'EDIT_CURRENT_SAPEUR_TELEPHONE',
  REMOVE_CURRENT_SAPEUR_TELEPHONE: 'REMOVE_CURRENT_SAPEUR_TELEPHONE',

  ADD_CURRENT_SAPEUR_FONCTION: 'ADD_CURRENT_SAPEUR_FONCTION',
  EDIT_CURRENT_SAPEUR_FONCTION: 'EDIT_CURRENT_SAPEUR_FONCTION',
  REMOVE_CURRENT_SAPEUR_FONCTION: 'REMOVE_CURRENT_SAPEUR_FONCTION',

  ADD_CURRENT_SAPEUR_GRADE: 'ADD_CURRENT_SAPEUR_GRADE',
  EDIT_CURRENT_SAPEUR_GRADE: 'EDIT_CURRENT_SAPEUR_GRADE',
  REMOVE_CURRENT_SAPEUR_GRADE: 'REMOVE_CURRENT_SAPEUR_GRADE',

  ADD_CURRENT_SAPEUR_COURS: 'ADD_CURRENT_SAPEUR_COURS',
  EDIT_CURRENT_SAPEUR_COURS: 'EDIT_CURRENT_SAPEUR_COURS',
  REMOVE_CURRENT_SAPEUR_COURS: 'REMOVE_CURRENT_SAPEUR_COURS',

  ADD_CURRENT_SAPEUR_GROUPES: 'ADD_CURRENT_SAPEUR_GROUPES',
  EDIT_CURRENT_SAPEUR_GROUPES: 'EDIT_CURRENT_SAPEUR_GROUPES',
  REMOVE_CURRENT_SAPEUR_GROUPES: 'REMOVE_CURRENT_SAPEUR_GROUPES',

  // Exercices
  UPDATE_EXERCICE_LISTE: 'UPDATE_EXERCICE_LISTE',
  ADD_EXERCICE: 'ADD_EXERCICE',
  REMOVE_EXERCICE: 'REMOVE_EXERCICE',
  SELECT_CURRENT_EXERCICE: 'SELECT_CURRENT_EXERCICE',
  UPDATE_EXERCICE_ABSENCES: 'UPDATE_EXERCICE_ABSENCES',
  UPDATE_EXERCICE_STATUT: 'UPDATE_EXERCICE_STATUT',
  UPDATE_EXERCICE_PRESENCE: 'UPDATE_EXERCICE_PRESENCE',
  UPDATE_CURRENT_EXERCICE_DATA: 'UPDATE_CURRENT_EXERCICE_DATA',
  UPDATE_CURRENT_EXERCICE_SAPEURS: 'UPDATE_CURRENT_EXERCICE_SAPEURS',
  REMOVE_CURRENT_EXERCICE_SAPEURS: 'REMOVE_CURRENT_EXERCICE_SAPEURS',
  ADD_HEURE: 'ADD_HEURE',
  UPDATE_HEURE: 'UPDATE_HEURE',
  REMOVE_HEURE: 'REMOVE_HEURE',

  // Exercices comptables
  UPDATE_EXERCICE_COMPTABLE_LISTE: 'UPDATE_EXERCICE_COMPTABLE_LISTE',
  SELECT_EXERCICE_COMPTABLE: 'SELECT_EXERCICE_COMPTABLE',
  ADD_EXERCICE_COMPTABLE: 'ADD_EXERCICE_COMPTABLE',
  UPDATE_EXERCICE_COMPTABLE: 'UPDATE_EXERCICE_COMPTABLE',
  REMOVE_EXERCICE_COMPTABLE: 'REMOVE_EXERCICE_COMPTABLE',

  // Interventions
  ADD_INTERVENTION: 'ADD_INTERVENTION',
  REMOVE_INTERVENTION: 'REMOVE_INTERVENTION',
  UPDATE_INTERVENTION_STATUT: 'UPDATE_INTERVENTION_STATUT',
  SELECT_CURRENT_INTERVENTION: 'SELECT_CURRENT_INTERVENTION',
  UPDATE_CURRENT_INTERVENTION_DATA: 'UPDATE_CURRENT_INTERVENTION_DATA',
  UPDATE_CURRENT_INTERVENTION_SAPEURS: 'UPDATE_CURRENT_INTERVENTION_SAPEURS',
  UPDATE_CURRENT_INTERVENTION_GROUPES: 'UPDATE_CURRENT_INTERVENTION_GROUPES',
  UPDATE_CURRENT_INTERVENTION_APPELS: 'UPDATE_CURRENT_INTERVENTION_APPELS',
  UPDATE_CURRENT_INTERVENTION_PHASES: 'UPDATE_CURRENT_INTERVENTION_PHASES',
  UPDATE_CURRENT_INTERVENTION_MISSIONS: 'UPDATE_CURRENT_INTERVENTION_MISSIONS',
  UPDATE_CURRENT_INTERVENTION_QUITTANCES:
    'UPDATE_CURRENT_INTERVENTION_QUITTANCES',
  UPDATE_CURRENT_INTERVENTION_VEHICULES:
    'UPDATE_CURRENT_INTERVENTION_VEHICULES',
  UPDATE_CURRENT_INTERVENTION_MATERIELS:
    'UPDATE_CURRENT_INTERVENTION_MATERIELS',

  ADD_CURRENT_INTERVENTION_MATERIEL: 'ADD_CURRENT_INTERVENTION_MATERIEL',
  EDIT_CURRENT_INTERVENTION_MATERIEL: 'EDIT_CURRENT_INTERVENTION_MATERIEL',
  REMOVE_CURRENT_INTERVENTION_MATERIEL: 'REMOVE_CURRENT_INTERVENTION_MATERIEL',

  EDIT_CURRENT_INTERVENTION_SAPEUR: 'EDIT_CURRENT_INTERVENTION_SAPEUR',
  REMOVE_CURRENT_INTERVENTION_SAPEUR: 'REMOVE_CURRENT_INTERVENTION_SAPEUR',

  REMOVE_CURRENT_INTERVENTION_GROUPES: 'REMOVE_CURRENT_INTERVENTION_GROUPES',
  REMOVE_CURRENT_INTERVENTION_VEHICULES:
    'REMOVE_CURRENT_INTERVENTION_VEHICULES',
  REMOVE_CURRENT_INTERVENTION_QUITTANCES:
    'REMOVE_CURRENT_INTERVENTION_QUITTANCES',

  REMOVE_CURRENT_INTERVENTION_MISSION: 'REMOVE_CURRENT_INTERVENTION_MISSION',
  REMOVE_CURRENT_INTERVENTION_APPEL: 'REMOVE_CURRENT_INTERVENTION_APPEL',

  UPDATE_CURRENT_MATERIEL: 'UPDATE_CURRENT_MATERIEL',
  UPDATE_CURRENT_MISSION: 'UPDATE_CURRENT_MISSION',
  UPDATE_CURRENT_APPEL: 'UPDATE_CURRENT_APPEL',

  // Interventions Params
  UPDATE_INTERVENTION_LISTE: 'UPDATE_INTERVENTION_LISTE',
  UPDATE_PHASE_TYPE_LISTE: 'UPDATE_PHASE_TYPE_LISTE',
  UPDATE_STAT_FEDERAL_LISTE: 'UPDATE_STAT_FEDERAL_LISTE',

  UPDATE_TYPE_INTERVENTION_LISTE: 'UPDATE_TYPE_INTERVENTION_LISTE',
  ADD_TYPE_INTERVENTION: 'ADD_TYPE_INTERVENTION',
  UPDATE_TYPE_INTERVENTION: 'UPDATE_TYPE_INTERVENTION',
  REMOVE_TYPE_INTERVENTION: 'REMOVE_TYPE_INTERVENTION',
  UPDATE_STAT_INTERVENTION_LISTE: 'UPDATE_STAT_INTERVENTION_LISTE',
  ADD_STAT_INTERVENTION: 'ADD_STAT_INTERVENTION',
  UPDATE_STAT_INTERVENTION: 'UPDATE_STAT_INTERVENTION',
  REMOVE_STAT_INTERVENTION: 'REMOVE_STAT_INTERVENTION',
  UPDATE_INTERVENTION_TRAITEMENT_LISTE: 'UPDATE_INTERVENTION_TRAITEMENT_LISTE',
  ADD_INTERVENTION_TRAITEMENT: 'ADD_INTERVENTION_TRAITEMENT',
  UPDATE_INTERVENTION_TRAITEMENT: 'UPDATE_INTERVENTION_TRAITEMENT',
  REMOVE_INTERVENTION_TRAITEMENT: 'REMOVE_INTERVENTION_TRAITEMENT',
  UPDATE_MATERIEL_LISTE: 'UPDATE_MATERIEL_LISTE',
  ADD_MATERIEL: 'ADD_MATERIEL',
  UPDATE_MATERIEL: 'UPDATE_MATERIEL',
  REMOVE_MATERIEL: 'REMOVE_MATERIEL',
  UPDATE_VEHICULE_LISTE: 'UPDATE_VEHICULE_LISTE',
  ADD_VEHICULE: 'ADD_VEHICULE',
  UPDATE_VEHICULE: 'UPDATE_VEHICULE',
  REMOVE_VEHICULE: 'REMOVE_VEHICULE',
  UPDATE_TELEPHONE_LISTE: 'UPDATE_TELEPHONE_LISTE',
  ADD_TELEPHONE: 'ADD_TELEPHONE',
  UPDATE_TELEPHONE: 'UPDATE_TELEPHONE',
  REMOVE_TELEPHONE: 'REMOVE_TELEPHONE',
  UPDATE_MISSION_LISTE: 'UPDATE_MISSION_LISTE',
  ADD_MISSION: 'ADD_MISSION',
  UPDATE_MISSION: 'UPDATE_MISSION',
  REMOVE_MISSION: 'REMOVE_MISSION',

  // Comptabilite
  ADD_ECRITURE: 'ADD_ECRITURE',
  UPDATE_ECRITURE: 'UPDATE_ECRITURE',
  REMOVE_ECRITURE: 'REMOVE_ECRITURE',

  UPDATE_FRAIS_INDEMNITES_TYPES: 'UPDATE_FRAIS_INDEMNITES_TYPES',
  UPDATE_ECRITURES_ANNUEL_TYPES_LISTE: 'UPDATE_ECRITURES_ANNUEL_TYPES_LISTE',
  SELECT_CURRENT_COMPTE: 'SELECT_CURRENT_COMPTE',
  UPDATE_CURRENT_COMPTE_ECRITURES: 'UPDATE_CURRENT_COMPTE_ECRITURES',
  UPDATE_ECRITURES_AMENDES: 'UPDATE_ECRITURES_AMENDES',
  UPDATE_ECRITURES_DIVERS_LISTE: 'UPDATE_ECRITURES_DIVERS_LISTE',
  UPDATE_ECRITURE_CATEGORIE_LISTE: 'UPDATE_ECRITURE_CATEGORIE_LISTE',

  UPDATE_COMPTE_LISTE: 'UPDATE_COMPTE_LISTE',
  ADD_COMPTE: 'ADD_COMPTE',
  UPDATE_COMPTE: 'UPDATE_COMPTE',
  REMOVE_COMPTE: 'REMOVE_COMPTE',
  ADD_ECRITURE_CATEGORIE: 'ADD_ECRITURE_CATEGORIE',
  UPDATE_ECRITURE_CATEGORIE: 'UPDATE_ECRITURE_CATEGORIE',
  REMOVE_ECRITURE_CATEGORIE: 'REMOVE_ECRITURE_CATEGORIE',
  ADD_FRAIS_INDEMNITE_ANNUEL: 'ADD_FRAIS_INDEMNITE_ANNUEL',
  UPDATE_FRAIS_INDEMNITE_ANNUEL: 'UPDATE_FRAIS_INDEMNITE_ANNUEL',
  REMOVE_FRAIS_INDEMNITE_ANNUEL: 'REMOVE_FRAIS_INDEMNITE_ANNUEL',
  ADD_INDEMNITE_ANNUEL: 'ADD_INDEMNITE_ANNUEL',
  UPDATE_INDEMNITE_ANNUEL: 'UPDATE_INDEMNITE_ANNUEL',
  REMOVE_INDEMNITE_ANNUEL: 'REMOVE_INDEMNITE_ANNUEL',
  ADD_FRAIS_INDEMNITE_ANNUEL_TYPE: 'ADD_FRAIS_INDEMNITE_ANNUEL_TYPE',
  UPDATE_FRAIS_INDEMNITE_ANNUEL_TYPE: 'UPDATE_FRAIS_INDEMNITE_ANNUEL_TYPE',
  REMOVE_FRAIS_INDEMNITE_ANNUEL_TYPE: 'REMOVE_FRAIS_INDEMNITE_ANNUEL_TYPE',
  ADD_INDEMNITE_ANNUEL_TYPE: 'ADD_INDEMNITE_ANNUEL_TYPE',
  UPDATE_INDEMNITE_ANNUEL_TYPE: 'UPDATE_INDEMNITE_ANNUEL_TYPE',
  REMOVE_INDEMNITE_ANNUEL_TYPE: 'REMOVE_INDEMNITE_ANNUEL_TYPE',
  ADD_INDEMNITE_COURS: 'ADD_INDEMNITE_COURS',
  UPDATE_INDEMNITE_COURS: 'UPDATE_INDEMNITE_COURS',
  REMOVE_INDEMNITE_COURS: 'REMOVE_INDEMNITE_COURS',
  ADD_INDEMNITE_EXERCICE: 'ADD_INDEMNITE_EXERCICE',
  UPDATE_INDEMNITE_EXERCICE: 'UPDATE_INDEMNITE_EXERCICE',
  REMOVE_INDEMNITE_EXERCICE: 'REMOVE_INDEMNITE_EXERCICE',
  ADD_INDEMNITE_INTERVENTION: 'ADD_INDEMNITE_INTERVENTION',
  UPDATE_INDEMNITE_INTERVENTION: 'UPDATE_INDEMNITE_INTERVENTION',
  REMOVE_INDEMNITE_INTERVENTION: 'REMOVE_INDEMNITE_INTERVENTION',

  // Paiements
  UPDATE_DECOMPTES: 'UPDATE_DECOMPTES',
  ADD_DECOMPTE: 'ADD_DECOMPTE',
  REMOVE_DECOMPTE: 'REMOVE_DECOMPTE',

  // Amendes
  UPDATE_AMENDE_LISTE: 'UPDATE_AMENDE_LISTE',

  // Unites
  UPDATE_UNITE_LISTE: 'UPDATE_UNITE_LISTE',
  ADD_UNITE: 'ADD_UNITE',
  UPDATE_UNITE: 'UPDATE_UNITE',
  REMOVE_UNITE: 'REMOVE_UNITE',

  // Controles medicaux
  UPDATE_CURRENT_CONTROLE_MEDICAL: 'UPDATE_CURRENT_CONTROLE_MEDICAL',
  RESET_CURRENT_CONTROLE_MEDICAL: 'RESET_CURRENT_CONTROLE_MEDICAL',
  REMOVE_CONTROLE_MEDICAL: 'REMOVE_CONTROLE_MEDICAL',
  UPDATE_CONTROLE_MEDICAUX_LISTE: 'UPDATE_CONTROLE_MEDICAUX_LISTE',
  REMOVE_JUSTIFICATIF: 'REMOVE_JUSTIFICATIF',

  // Controles médicaux types
  UPDATE_CONTROLE_MEDICAUX_TYPES_LISTE: 'UPDATE_CONTROLE_MEDICAUX_TYPES_LISTE',
  ADD_CONTROLE_MEDICAUX_TYPES: 'ADD_CONTROLE_MEDICAUX_TYPES',
  UPDATE_CONTROLE_MEDICAUX_TYPES: 'UPDATE_CONTROLE_MEDICAUX_TYPES',
  REMOVE_CONTROLE_MEDICAUX_TYPES: 'REMOVE_CONTROLE_MEDICAUX_TYPES',

  // Médecins
  UPDATE_MEDECIN_LISTE: 'UPDATE_MEDECIN_LISTE',
  ADD_MEDECIN: 'ADD_MEDECIN',
  UPDATE_MEDECIN: 'UPDATE_MEDECIN',
  REMOVE_MEDECIN: 'REMOVE_MEDECIN',

  // Statistiques
  UPDATE_STATISTIQUE_CIVILITE: 'UPDATE_STATISTIQUE_CIVILITE',
  UPDATE_STATISTIQUE_FONCTION: 'UPDATE_STATISTIQUE_FONCTION',
  UPDATE_STATISTIQUE_GRADE: 'UPDATE_STATISTIQUE_GRADE',
  UPDATE_STATISTIQUE_PERMIS: 'UPDATE_STATISTIQUE_PERMIS',
  UPDATE_STATISTIQUE_VEHICULE: 'UPDATE_STATISTIQUE_VEHICULE',
  UPDATE_STATISTIQUE_MATERIEL: 'UPDATE_STATISTIQUE_MATERIEL',
  UPDATE_STATISTIQUE_PRESENCE: 'UPDATE_STATISTIQUE_PRESENCE',
  UPDATE_STATISTIQUE_STAT_FEDERAL: 'UPDATE_STATISTIQUE_STAT_FEDERAL',
  UPDATE_STATISTIQUE_TYPE_INTERVENTION: 'UPDATE_STATISTIQUE_TYPE_INTERVENTION',
  UPDATE_STATISTIQUE_INTERVENTION_TRAITEMENT:
    'UPDATE_STATISTIQUE_INTERVENTION_TRAITEMENT',
  UPDATE_STATISTIQUE_CATEGORIE_COMPTABLE:
    'UPDATE_STATISTIQUE_CATEGORIE_COMPTABLE',
  UPDATE_STATISTIQUE_COMPTE: 'UPDATE_STATISTIQUE_COMPTE',
  UPDATE_STATISTIQUE_MODULE_COMPTABLE: 'UPDATE_STATISTIQUE_MODULE_COMPTABLE',

  // Matériel personnel
  UPDATE_MAT_PERSO_EVENT_TYPE_LISTE: 'UPDATE_MAT_PERSO_EVENT_TYPE_LISTE',
  ADD_MAT_PERSO_EVENT_TYPE: 'ADD_MAT_PERSO_EVENT_TYPE',
  UPDATE_MAT_PERSO_EVENT_TYPE: 'UPDATE_MAT_PERSO_EVENT_TYPE',
  REMOVE_MAT_PERSO_EVENT_TYPE: 'REMOVE_MAT_PERSO_EVENT_TYPE',

  UPDATE_MAT_PERSO_ALERTE_TYPE_LISTE: 'UPDATE_MAT_PERSO_ALERTE_TYPE_LISTE',
  ADD_MAT_PERSO_ALERTE_TYPE: 'ADD_MAT_PERSO_ALERTE_TYPE',
  UPDATE_MAT_PERSO_ALERTE_TYPE: 'UPDATE_MAT_PERSO_ALERTE_TYPE',
  REMOVE_MAT_PERSO_ALERTE_TYPE: 'REMOVE_MAT_PERSO_ALERTE_TYPE',

  UPDATE_MAT_PERSO_TYPE_LISTE: 'UPDATE_MAT_PERSO_TYPE_LISTE',
  ADD_MAT_PERSO_TYPE: 'ADD_MAT_PERSO_TYPE',
  UPDATE_MAT_PERSO_TYPE: 'UPDATE_MAT_PERSO_TYPE',
  REMOVE_MAT_PERSO_TYPE: 'REMOVE_MAT_PERSO_TYPE',

  UPDATE_MAT_PERSO_CATEGORIE_LISTE: 'UPDATE_MAT_PERSO_CATEGORIE_LISTE',
  ADD_MAT_PERSO_CATEGORIE: 'ADD_MAT_PERSO_CATEGORIE',
  UPDATE_MAT_PERSO_CATEGORIE: 'UPDATE_MAT_PERSO_CATEGORIE',
  REMOVE_MAT_PERSO_CATEGORIE: 'REMOVE_MAT_PERSO_CATEGORIE',

  UPDATE_MAT_PERSO_LISTE: 'UPDATE_MAT_PERSO_LISTE',
  REMOVE_MAT_PERSO: 'REMOVE_MAT_PERSO',
  UPDATE_MAT_PERSO_A_RECUPERER_LISTE: 'UPDATE_MAT_PERSO_A_RECUPERER_LISTE',

  UPDATE_MAT_PERSO_ALERTE_LISTE: 'UPDATE_MAT_PERSO_ALERTE_LISTE',
  ADD_MAT_PERSO_ALERTE: 'ADD_MAT_PERSO_ALERTE',
  UPDATE_MAT_PERSO_ALERTE: 'UPDATE_MAT_PERSO_ALERTE',
  REMOVE_MAT_PERSO_ALERTE: 'REMOVE_MAT_PERSO_ALERTE',

  // Cours
  UPDATE_COURS_SAPEUR_LISTE: 'UPDATE_COURS_SAPEUR_LISTE',
  UPDATE_COURS_SAPEUR_ECRITURE_STATUT: 'UPDATE_COURS_SAPEUR_ECRITURE_STATUT',

  // Travaux
  UPDATE_TRAVAIL_LISTE: 'UPDATE_TRAVAIL_LISTE',
  ADD_TRAVAIL: 'ADD_TRAVAIL',
  UPDATE_TRAVAIL: 'UPDATE_TRAVAIL',
  UPDATE_TRAVAIL_STATUT: 'UPDATE_TRAVAIL_STATUT',
  REMOVE_TRAVAIL: 'REMOVE_TRAVAIL',

  UPDATE_TRAVAIL_TYPE_LISTE: 'UPDATE_TRAVAIL_TYPE_LISTE',
  ADD_TRAVAIL_TYPE: 'ADD_TRAVAIL_TYPE',
  UPDATE_TRAVAIL_TYPE: 'UPDATE_TRAVAIL_TYPE',
  REMOVE_TRAVAIL_TYPE: 'REMOVE_TRAVAIL_TYPE',
};
