export default {
  SHOW_MODAL: 'SHOW_MODAL',
  HIDE_MODAL: 'HIDE_MODAL',

  //Sapeurs base data
  UPDATE_PERMIS_LIST: 'UPDATE_PERMIS_LIST',
  UPDATE_TELEPHONE_LIST: 'UPDATE_TELEPHONE_LIST',
  UPDATE_CIVILITE_LIST: 'UPDATE_CIVILITE_LIST',
  UPDATE_LOCALITE_LIST: 'UPDATE_LOCALITE_LIST',
  UPDATE_COURS_LIST: 'UPDATE_COURS_LIST',
  UPDATE_GRADE_LIST: 'UPDATE_GRADE_LIST',
  UPDATE_FONCTION_LIST: 'UPDATE_FONCTION_LIST',
  UPDATE_GROUPE_LIST: 'UPDATE_GROUPE_LIST',

  //Groupes
  UPDATE_GROUPE_SAPEUR_LIST: 'UPDATE_GROUPE_SAPEUR_LIST',

  //Exercices
  UPDATE_EXCUSE_TYPE_LIST: 'UPDATE_EXCUSE_TYPE_LIST',
  SELECT_EXCUSE_TYPE: 'SELECT_EXCUSE_TYPE',
  UPDATE_EXERCICE_CATEGORIE_LIST: 'UPDATE_EXERCICE_CATEGORIE_LIST',

  UPDATE_EXERCICE_LIST: 'UPDATE_EXERCICE_LIST',
  UPDATE_INTERVENTION_LIST: 'UPDATE_INTERVENTION_LIST',

  //Sapeurs edit
  SELECT_CURRENT_SAPEUR: 'SELECT_CURRENT_SAPEUR',
  UPDATE_SAPEURS_LIST: 'UPDATE_SAPEURS_LIST',
  UPDATE_CURRENT_SAPEUR_DATA: 'UPDATE_CURRENT_SAPEUR_DATA',
  UPDATE_CURRENT_SAPEUR_PERMIS: 'UPDATE_CURRENT_SAPEUR_PERMIS',
  UPDATE_CURRENT_SAPEUR_TELEPHONES: 'UPDATE_CURRENT_SAPEUR_TELEPHONES',
  UPDATE_CURRENT_SAPEUR_GROUPES: 'UPDATE_CURRENT_SAPEUR_GROUPES',
  UPDATE_CURRENT_SAPEUR_GRADES: 'UPDATE_CURRENT_SAPEUR_GRADES',
  UPDATE_CURRENT_SAPEUR_FONCTIONS: 'UPDATE_CURRENT_SAPEUR_FONCTIONS',
  UPDATE_CURRENT_SAPEUR_MUTATIONS: 'UPDATE_CURRENT_SAPEUR_MUTATIONS',
  UPDATE_CURRENT_SAPEUR_MATERIEL: 'UPDATE_CURRENT_SAPEUR_MATERIEL',
  UPDATE_CURRENT_SAPEUR_BANQUE: 'UPDATE_CURRENT_SAPEUR_BANQUE',
  UPDATE_CURRENT_SAPEUR_COURS: 'UPDATE_CURRENT_SAPEUR_COURS',

  UPDATE_CURRENT_FONCTION: 'UPDATE_CURRENT_FONCTION',
  UPDATE_CURRENT_GRADE: 'UPDATE_CURRENT_GRADE',
  UPDATE_CURRENT_COURS: 'UPDATE_CURRENT_COURS',
  UPDATE_CURRENT_MUTATION: 'UPDATE_CURRENT_MUTATION',

  ADD_CURRENT_SAPEUR_MUTATION: 'ADD_CURRENT_SAPEUR_MUTATION',
  EDIT_CURRENT_SAPEUR_MUTATION: 'EDIT_CURRENT_SAPEUR_MUTATION',
  REMOVE_CURRENT_SAPEUR_MUTATION: 'REMOVE_CURRENT_SAPEUR_MUTATION',

  ADD_CURRENT_SAPEUR_PERMIS: 'ADD_CURRENT_SAPEUR_PERMIS',
  EDIT_CURRENT_SAPEUR_PERMIS: 'EDIT_CURRENT_SAPEUR_PERMIS',
  REMOVE_CURRENT_SAPEUR_PERMIS: 'REMOVE_CURRENT_SAPEUR_PERMIS',

  ADD_CURRENT_SAPEUR_TELEPHONE: 'ADD_CURRENT_SAPEUR_TELEPHONE',
  EDIT_CURRENT_SAPEUR_TELEPHONE: 'EDIT_CURRENT_SAPEUR_TELEPHONE',
  REMOVE_CURRENT_SAPEUR_TELEPHONE: 'REMOVE_CURRENT_SAPEUR_TELEPHONE',

  ADD_CURRENT_SAPEUR_FONCTION: 'ADD_CURRENT_SAPEUR_FONCTION',
  EDIT_CURRENT_SAPEUR_FONCTION: 'EDIT_CURRENT_SAPEUR_FONCTION',
  REMOVE_CURRENT_SAPEUR_FONCTION: 'REMOVE_CURRENT_SAPEUR_FONCTION',

  ADD_CURRENT_SAPEUR_GRADE: 'ADD_CURRENT_SAPEUR_GRADE',
  EDIT_CURRENT_SAPEUR_GRADE: 'EDIT_CURRENT_SAPEUR_GRADE',
  REMOVE_CURRENT_SAPEUR_GRADE: 'REMOVE_CURRENT_SAPEUR_GRADE',

  ADD_CURRENT_SAPEUR_COURS: 'ADD_CURRENT_SAPEUR_COURS',
  EDIT_CURRENT_SAPEUR_COURS: 'EDIT_CURRENT_SAPEUR_COURS',
  REMOVE_CURRENT_SAPEUR_COURS: 'REMOVE_CURRENT_SAPEUR_COURS',

  ADD_CURRENT_SAPEUR_GROUPES: 'ADD_CURRENT_SAPEUR_GROUPES',
  EDIT_CURRENT_SAPEUR_GROUPES: 'EDIT_CURRENT_SAPEUR_GROUPES',
  REMOVE_CURRENT_SAPEUR_GROUPES: 'REMOVE_CURRENT_SAPEUR_GROUPES',

  //Exercices
  ADD_EXERCICE: 'ADD_EXERCICE',
  SELECT_CURRENT_EXERCICE: 'SELECT_CURRENT_EXERCICE',
  UPDATE_CURRENT_EXERCICE_DATA: 'UPDATE_CURRENT_EXERCICE_DATA',
  UPDATE_CURRENT_EXERCICE_SAPEURS: 'UPDATE_CURRENT_EXERCICE_SAPEURS',
  REMOVE_CURRENT_EXERCICE_SAPEURS: 'REMOVE_CURRENT_EXERCICE_SAPEURS',

  //Exercices comptables
  UPDATE_EXERCICE_COMPTABLE_LIST: 'UPDATE_EXERCICE_COMPTABLE_LIST',
  SELECT_EXERCICE_COMPTABLE: 'SELECT_EXERCICE_COMPTABLE',

  //Interventions
  ADD_INTERVENTION: 'ADD_INTERVENTION',
  SELECT_CURRENT_INTERVENTION: 'SELECT_CURRENT_INTERVENTION',
  UPDATE_CURRENT_INTERVENTION_DATA: 'UPDATE_CURRENT_INTERVENTION_DATA',
  UPDATE_CURRENT_INTERVENTION_SAPEURS: 'UPDATE_CURRENT_INTERVENTION_SAPEURS',

  UPDATE_TYPE_INTERVENTION_LIST: 'UPDATE_TYPE_INTERVENTION_LIST',
  UPDATE_STAT_FEDERAL_LIST: 'UPDATE_STAT_FEDERAL_LIST',
  UPDATE_INTERVENTION_TRAITEMENT_LIST: 'UPDATE_INTERVENTION_TRAITEMENT_LIST'
}
