export default {
  UPDATE_PERMIS_LIST: 'UPDATE_PERMIS_LIST',
  UPDATE_CIVILITE_LIST: 'UPDATE_CIVILITE_LIST',
  UPDATE_LOCALITE_LIST: 'UPDATE_LOCALITE_LIST',

  UPDATE_SAPEURS_LIST: 'UPDATE_SAPEURS_LIST',
  UPDATE_CURRENT_SAPEUR: 'UPDATE_CURRENT_SAPEUR',
  UPDATE_CURRENT_SAPEUR_PERMIS: 'UPDATE_CURRENT_SAPEUR_PERMIS',
  UPDATE_CURRENT_SAPEUR_TELEPHONES: 'UPDATE_CURRENT_SAPEUR_TELEPHONES',
  UPDATE_CURRENT_SAPEUR_GROUPES: 'UPDATE_CURRENT_SAPEUR_GROUPES',
  UPDATE_CURRENT_SAPEUR_GRADES: 'UPDATE_CURRENT_SAPEUR_GRADES',
  UPDATE_CURRENT_SAPEUR_FONCTIONS: 'UPDATE_CURRENT_SAPEUR_FONCTIONS',
  UPDATE_CURRENT_SAPEUR_MUTATIONS: 'UPDATE_CURRENT_SAPEUR_MUTATIONS',
  UPDATE_CURRENT_SAPEUR_MATERIEL: 'UPDATE_CURRENT_SAPEUR_MATERIEL',
  UPDATE_CURRENT_SAPEUR_BANQUE: 'UPDATE_CURRENT_SAPEUR_BANQUE',
  UPDATE_CURRENT_SAPEUR_COURS: 'UPDATE_CURRENT_SAPEUR_COURS',

  ADD_CURRENT_SAPEUR_PERMIS: 'ADD_CURRENT_SAPEUR_PERMIS',
  EDIT_CURRENT_SAPEUR_PERMIS: 'EDIT_CURRENT_SAPEUR_PERMIS',
  REMOVE_CURRENT_SAPEUR_PERMIS: 'REMOVE_CURRENT_SAPEUR_PERMIS'
}
