export default {
  UPDATE_PERMIS_LIST: 'UPDATE_PERMIS_LIST',
  UPDATE_CIVILITE_LIST: 'UPDATE_CIVILITE_LIST',

  UPDATE_SAPEURS_LIST: 'UPDATE_SAPEURS_LIST',
  UPDATE_CURRENT_SAPEUR: 'UPDATE_CURRENT_SAPEUR'
}
